disabled_rules:
  - cyclomatic_complexity
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - extension_access_modifier
  - file_header
  - function_body_length
  - identifier_name
  - implicitly_unwrapped_optional
  - large_tuple
  - line_length
  - todo # next to enable again
  - xctfail_message
  - unused_optional_binding
  - no_grouping_extension
excluded:
  - .build
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - strict_fileprivate
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
